#    This file contains the mrf24j40 register definitions. They were parsed from the datasheet
#    No claim for correctness nor completeness.

#    Copyright (C) 2013  Jasper Buesch

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Author: Jasper Buesch; jasper.buesch@gmail.com

short_addr_registers = {
"RXMCR": 0x00,
"PANIDL": 0x01,
"PANIDH": 0x02,
"SADRL": 0x03,
"SADRH": 0x04,
"EADR0": 0x05,
"EADR1": 0x06,
"EADR2": 0x07,
"EADR3": 0x08,
"EADR4": 0x09,
"EADR5": 0x0A,
"EADR6": 0x0B,
"EADR7": 0x0C,
"RXFLUSH": 0x0D,
"ORDER": 0x10,
"TXMCR": 0x11,
"ACKTMOUT": 0x12,
"ESLOTG1": 0x13,
"SYMTICKL": 0x14,
"SYMTICKH": 0x15,
"PACON0": 0x16,
"PACON1": 0x17,
"PACON2": 0x18,
"TXBCON0": 0x1A,
"TXNCON": 0x1B,
"TXG1CON": 0x1C,
"TXG2CON": 0x1D,
"ESLOTG23": 0x1E,
"ESLOTG45": 0x1F,
"ESLOTG67": 0x20,
"TXPEND": 0x21,
"WAKECON": 0x22,
"FRMOFFSET": 0x23,
"TXSTAT": 0x24,
"TXBCON1": 0x25,
"GATECLK": 0x26,
"TXTIME": 0x27,
"HSYMTMRL": 0x28,
"HSYMTMRH": 0x29,
"SOFTRST": 0x2A,
"SECCON0": 0x2C,
"SECCON1": 0x2D,
"TXSTBL": 0x2E,
"RXSR": 0x30,
"INTSTAT": 0x31,
"INTCON": 0x32,
"GPIO": 0x33,
"TRISGPIO": 0x34,
"SLPACK": 0x35,
"RFCTL": 0x36,
"SECCR2": 0x37,
"BBREG0": 0x38,
"BBREG1": 0x39,
"BBREG2": 0x3A,
"BBREG3": 0x3B,
"BBREG4": 0x3C,
"BBREG6": 0x3E,
"CCAEDTH": 0x3F}

long_addr_registers = {
"RFCON0": 0x200,
"RFCON1": 0x201,
"RFCON2": 0x202,
"RFCON3": 0x203,
"RFCON5": 0x205,
"RFCON6": 0x206,
"RFCON7": 0x207,
"RFCON8": 0x208,
"SLPCAL0": 0x209,
"SLPCAL1": 0x20A,
"SLPCAL2": 0x20B,
"RFSTATE": 0x20F,
"RSSI": 0x210,
"SLPCON0": 0x211,
"SLPCON1": 0x220,
"WAKETIMEL": 0x222,
"WAKETIMEH": 0x223,
"REMCNTL": 0x224,
"REMCNTH": 0x225,
"MAINCNT0": 0x226,
"MAINCNT1": 0x227,
"MAINCNT2": 0x228,
"MAINCNT3": 0x229,
"TESTMODE": 0x22F,
"ASSOEADR0": 0x230,
"ASSOEADR1": 0x231,
"ASSOEADR2": 0x232,
"ASSOEADR3": 0x233,
"ASSOEADR4": 0x234,
"ASSOEADR5": 0x235,
"ASSOEADR6": 0x236,
"ASSOEADR7": 0x237,
"ASSOSADR0": 0x238,
"ASSOSADR1": 0x239,
"UPNONCE0": 0x240,
"UPNONCE1": 0x241,
"UPNONCE2": 0x242,
"UPNONCE3": 0x243,
"UPNONCE4": 0x244,
"UPNONCE5": 0x245,
"UPNONCE6": 0x246,
"UPNONCE7": 0x247,
"UPNONCE8": 0x248,
"UPNONCE9": 0x249,
"UPNONCE10": 0x24A,
"UPNONCE11": 0x24B,
"UPNONCE12": 0x24C}

register_fields = {
'20MRECVR': [{'shift': 4, 'register': 'RFCON6', 'bits': 1}],
'BATEN': [{'shift': 3, 'register': 'RFCON6', 'bits': 1}],
'BATIND': [{'shift': 5, 'register': 'RXSR', 'bits': 1}],
'BATLIFEXT': [{'shift': 6, 'register': 'TXMCR', 'bits': 1}],
'BATTH': [{'shift': 4, 'register': 'RFCON5', 'bits': 4}],
'BCNONLY': [{'shift': 1, 'register': 'RXFLUSH', 'bits': 1}],
'BO': [{'shift': 4, 'register': 'ORDER', 'bits': 4}],
'CAP': [{'shift': 0, 'register': 'ESLOTG1', 'bits': 4}],
'CCACSTH': [{'shift': 2, 'register': 'BBREG2', 'bits': 4}],
'CCAEDTH': [{'shift': 0, 'register': 'CCAEDTH', 'bits': 8}],
'CCAFAIL': [{'shift': 5, 'register': 'TXSTAT', 'bits': 1}],
'CCAMODE': [{'shift': 6, 'register': 'BBREG2', 'bits': 2}],
'CHANNEL': [{'shift': 4, 'register': 'RFCON0', 'bits': 4}],
'CLKOUTEN': [{'shift': 5, 'register': 'SLPCON1', 'bits': 1}],
'CLKOUTMODE': [{'shift': 0, 'register': 'RFCON7', 'bits': 2}],
'CMDONLY': [{'shift': 3, 'register': 'RXFLUSH', 'bits': 1}],
'COORD': [{'shift': 2, 'register': 'RXMCR', 'bits': 1}],
'CSMABF': [{'shift': 0, 'register': 'TXMCR', 'bits': 3}],
'CSTH': [{'shift': 5, 'register': 'BBREG4', 'bits': 3}],
'DATAONLY': [{'shift': 2, 'register': 'RXFLUSH', 'bits': 1}],
'DISDEC': [{'shift': 1, 'register': 'SECCON1', 'bits': 1}],
'DISENC': [{'shift': 0, 'register': 'SECCON1', 'bits': 1}],
'DRPACK': [{'shift': 7, 'register': 'ACKTMOUT', 'bits': 1}],
'ERRPKT': [{'shift': 1, 'register': 'RXMCR', 'bits': 1}],
'FIFOEN': [{'shift': 7, 'register': 'PACON2', 'bits': 1}],
'FPACK': [{'shift': 0, 'register': 'TXPEND', 'bits': 1}],
'FPSTAT': [{'shift': 4, 'register': 'TXNCON', 'bits': 1}],
'GPIO': [{'shift': 0, 'register': 'GPIO', 'bits': 6}],
'GTS1': [{'shift': 4, 'register': 'ESLOTG1', 'bits': 4}],
'GTS2': [{'shift': 0, 'register': 'ESLOTG23', 'bits': 4}],
'GTS3': [{'shift': 4, 'register': 'ESLOTG23', 'bits': 4}],
'GTS4': [{'shift': 0, 'register': 'ESLOTG45', 'bits': 4}],
'GTS5': [{'shift': 4, 'register': 'ESLOTG45', 'bits': 4}],
'GTS6': [{'shift': 0, 'register': 'ESLOTG67', 'bits': 4}],
'GTSON': [{'shift': 3, 'register': 'GATECLK', 'bits': 1}],
'GTSSWITCH': [{'shift': 1, 'register': 'TXPEND', 'bits': 1}],
'HSYMTMR': [{'shift': 0, 'register': 'HSYMTMRL', 'bits': 8}, {'shift': 2, 'register': 'HSYMTMRH', 'bits': 6}],
'HSYMTMRIE': [{'shift': 5, 'register': 'INTCON', 'bits': 1}],
'HSYMTMRIF': [{'shift': 5, 'register': 'INTSTAT', 'bits': 1}],
'IMMWAKE': [{'shift': 7, 'register': 'WAKECON', 'bits': 1}],
'INDIRECT': [{'shift': 3, 'register': 'TXNCON', 'bits': 1}],
'INTEDGE': [{'shift': 1, 'register': 'SLPCON0', 'bits': 1}],
'INTL': [{'shift': 0, 'register': 'WAKECON', 'bits': 1}],
'MACMINBE': [{'shift': 3, 'register': 'TXMCR', 'bits': 2}],
'MAINCNT': [{'shift': 0, 'register': 'MAINCNT0', 'bits': 8}, {'shift': 0, 'register': 'MAINCNT1', 'bits': 8}, {'shift': 0, 'register': 'MAINCNT2', 'bits': 8}, {'shift': 0, 'register': 'MAINCNT3', 'bits': 2}],
'MAWD': [{'shift': 0, 'register': 'ACKTMOUT', 'bits': 7}],
'MLIFS': [{'shift': 2, 'register': 'TXPEND', 'bits': 6}],
'MSIFS': [{'shift': 0, 'register': 'TXSTBL', 'bits': 4}],
'NOACKRSP': [{'shift': 5, 'register': 'RXMCR', 'bits': 1}],
'NOCSMA': [{'shift': 7, 'register': 'TXMCR', 'bits': 1}],
'OFFSET': [{'shift': 0, 'register': 'FRMOFFSET', 'bits': 8}],
'PANCOORD': [{'shift': 3, 'register': 'RXMCR', 'bits': 1}],
'PANID': [{'shift': 0, 'register': 'PANIDL', 'bits': 8}, {'shift': 0, 'register': 'PANIDH', 'bits': 8}],
'PAONT': [{'shift': 0, 'register': 'PACON0', 'bits': 8}],
'PAONTS': [{'shift': 1, 'register': 'PACON1', 'bits': 4}],
'PLLEN': [{'shift': 7, 'register': 'RFCON2', 'bits': 1}],
'PRECNT': [{'shift': 2, 'register': 'BBREG4', 'bits': 3}],
'PREDETTH': [{'shift': 1, 'register': 'BBREG3', 'bits': 3}],
'PREVALIDTH': [{'shift': 4, 'register': 'BBREG3', 'bits': 4}],
'PROMI': [{'shift': 0, 'register': 'RXMCR', 'bits': 1}],
'REGWAKE': [{'shift': 6, 'register': 'WAKECON', 'bits': 1}],
'REMCNT': [{'shift': 0, 'register': 'REMCNTL', 'bits': 8}, {'shift': 0, 'register': 'REMCNTH', 'bits': 8}],
'RFOPT': [{'shift': 0, 'register': 'RFCON0', 'bits': 4}],
'RFSTATE': [{'shift': 5, 'register': 'RFSTATE', 'bits': 3}],
'RFSTBL': [{'shift': 4, 'register': 'TXSTBL', 'bits': 4}],
'RFVCO': [{'shift': 4, 'register': 'RFCON8', 'bits': 1}],
'RSSI': [{'shift': 0, 'register': 'RSSI', 'bits': 8}],
'RSSINUM': [{'shift': 4, 'register': 'TXBCON1', 'bits': 2}],
'RSSIWAIT': [{'shift': 3, 'register': 'TESTMODE', 'bits': 2}],
'RSTBB': [{'shift': 1, 'register': 'SOFTRST', 'bits': 1}],
'RSTMAC': [{'shift': 0, 'register': 'SOFTRST', 'bits': 1}],
'RSTPWR': [{'shift': 2, 'register': 'SOFTRST', 'bits': 1}],
'RXCIPHER': [{'shift': 3, 'register': 'SECCON0', 'bits': 3}],
'RXDECINV': [{'shift': 2, 'register': 'BBREG1', 'bits': 1}],
'RXFLUSH': [{'shift': 0, 'register': 'RXFLUSH', 'bits': 1}],
'RXIE': [{'shift': 3, 'register': 'INTCON', 'bits': 1}],
'RXIF': [{'shift': 3, 'register': 'INTSTAT', 'bits': 1}],
'SECDECERR': [{'shift': 2, 'register': 'RXSR', 'bits': 1}],
'SADR': [{'shift': 0, 'register': 'SADRL', 'bits': 8},{'shift': 0, 'register': 'SADRH', 'bits': 8}],
'SECIE': [{'shift': 4, 'register': 'INTCON', 'bits': 1}],
'SECIF': [{'shift': 4, 'register': 'INTSTAT', 'bits': 1}],
'SECIGNORE': [{'shift': 7, 'register': 'SECCON0', 'bits': 1}],
'SECSTART': [{'shift': 6, 'register': 'SECCON0', 'bits': 1}],
'SLOTTED': [{'shift': 5, 'register': 'TXMCR', 'bits': 1}],
'SLPACK': [{'shift': 7, 'register': 'SLPACK', 'bits': 1}],
'SLPCAL': [{'shift': 0, 'register': 'SLPCAL0', 'bits': 8}],
'SLPCAL1': [{'shift': 2, 'register': 'SLPCAL1', 'bits': 6}],
'SLPCALEN': [{'shift': 4, 'register': 'SLPCAL2', 'bits': 1}],
'SLPCALRDY': [{'shift': 7, 'register': 'SLPCAL2', 'bits': 1}],
'SLPCLKDIV': [{'shift': 0, 'register': 'SLPCON1', 'bits': 5}],
'SLPCLKEN': [{'shift': 0, 'register': 'SLPCON0', 'bits': 1}],
'SLPCLKSEL': [{'shift': 6, 'register': 'RFCON7', 'bits': 2}],
'SLPIE': [{'shift': 7, 'register': 'INTCON', 'bits': 1}],
'SLPIF': [{'shift': 7, 'register': 'INTSTAT', 'bits': 1}],
'SO': [{'shift': 0, 'register': 'ORDER', 'bits': 4}],
'STARTCNT': [{'shift': 7, 'register': 'MAINCNT3', 'bits': 1}],
'TESTMODE': [{'shift': 0, 'register': 'TESTMODE', 'bits': 3}],
'TICKP': [{'shift': 0, 'register': 'SYMTICKL', 'bits': 8}],
'TRISGP': [{'shift': 0, 'register': 'TRISGPIO', 'bits': 6}],
'TURBO': [{'shift': 0, 'register': 'BBREG0', 'bits': 1}],
'TURNTIME': [{'shift': 4, 'register': 'TXTIME', 'bits': 4}],
'TXBCIPHER': [{'shift': 4, 'register': 'SECCON1', 'bits': 3}],
'TXBMSK': [{'shift': 7, 'register': 'TXBCON1', 'bits': 1}],
'TXBSECEN': [{'shift': 1, 'register': 'TXBCON0', 'bits': 1}],
'TXBTRIG': [{'shift': 0, 'register': 'TXBCON0', 'bits': 1}],
'TXFIL': [{'shift': 7, 'register': 'RFCON6', 'bits': 1}],
'TXG1ACKREQ': [{'shift': 2, 'register': 'TXG1CON', 'bits': 1}],
'TXG1CIPHER': [{'shift': 0, 'register': 'SECCR2', 'bits': 3}],
'TXG1FNT': [{'shift': 3, 'register': 'TXSTAT', 'bits': 1}],
'TXG1IE': [{'shift': 1, 'register': 'INTCON', 'bits': 1}],
'TXG1IF': [{'shift': 1, 'register': 'INTSTAT', 'bits': 1}],
'TXG1RETRY': [{'shift': 6, 'register': 'TXG1CON', 'bits': 2}],
'TXG1SECEN': [{'shift': 1, 'register': 'TXG1CON', 'bits': 1}],
'TXG1SLOT': [{'shift': 3, 'register': 'TXG1CON', 'bits': 3}],
'TXG1STAT': [{'shift': 1, 'register': 'TXSTAT', 'bits': 1}],
'TXG1TRIG': [{'shift': 0, 'register': 'TXG1CON', 'bits': 1}],
'TXG2ACKREQ': [{'shift': 2, 'register': 'TXG2CON', 'bits': 1}],
'TXG2CIPHER': [{'shift': 3, 'register': 'SECCR2', 'bits': 3}],
'TXG2FNT': [{'shift': 4, 'register': 'TXSTAT', 'bits': 1}],
'TXG2IE': [{'shift': 2, 'register': 'INTCON', 'bits': 1}],
'TXG2IF': [{'shift': 2, 'register': 'INTSTAT', 'bits': 1}],
'TXG2RETRY': [{'shift': 6, 'register': 'TXG2CON', 'bits': 2}],
'TXG2SECEN': [{'shift': 1, 'register': 'TXG2CON', 'bits': 1}],
'TXG2SLOT': [{'shift': 3, 'register': 'TXG2CON', 'bits': 3}],
'TXG2STAT': [{'shift': 2, 'register': 'TXSTAT', 'bits': 1}],
'TXG2TRIG': [{'shift': 0, 'register': 'TXG2CON', 'bits': 1}],
'TXNACKREQ': [{'shift': 2, 'register': 'TXNCON', 'bits': 1}],
'TXNCIPHER': [{'shift': 0, 'register': 'SECCON0', 'bits': 3}],
'TXNIE': [{'shift': 0, 'register': 'INTCON', 'bits': 1}],
'TXNIF': [{'shift': 0, 'register': 'INTSTAT', 'bits': 1}],
'TXNRETRY': [{'shift': 6, 'register': 'TXSTAT', 'bits': 2}],
'TXNSECEN': [{'shift': 1, 'register': 'TXNCON', 'bits': 1}],
'TXNSTAT': [{'shift': 0, 'register': 'TXSTAT', 'bits': 1}],
'TXNTRIG': [{'shift': 0, 'register': 'TXNCON', 'bits': 1}],
'TXONT': [{'shift': 1, 'register': 'SYMTICKH', 'bits': 7}],
'TXONTS': [{'shift': 2, 'register': 'PACON2', 'bits': 4}],
'TXPWRL': [{'shift': 6, 'register': 'RFCON3', 'bits': 2}],
'TXPWRS': [{'shift': 3, 'register': 'RFCON3', 'bits': 3}],
'UPDEC': [{'shift': 7, 'register': 'SECCR2', 'bits': 1}],
'UPENC': [{'shift': 6, 'register': 'SECCR2', 'bits': 1}],
'UPSECERR': [{'shift': 6, 'register': 'RXSR', 'bits': 1}],
'VCOOPT': [{'shift': 0, 'register': 'RFCON1', 'bits': 8}],
'WAKECNT': [{'shift': 0, 'register': 'SLPACK', 'bits': 7}],
'WAKEIE': [{'shift': 6, 'register': 'INTCON', 'bits': 1}],
'WAKEIF': [{'shift': 6, 'register': 'INTSTAT', 'bits': 1}],
'WAKEPAD': [{'shift': 5, 'register': 'RXFLUSH', 'bits': 1}],
'WAKEPOL': [{'shift': 6, 'register': 'RXFLUSH', 'bits': 1}],
'WAKETIME': [{'shift': 0, 'register': 'WAKETIMEL', 'bits': 8}, {'shift': 0, 'register': 'WAKETIMEH', 'bits': 3}],
'WU/BCN': [{'shift': 6, 'register': 'TXBCON1', 'bits': 1}]
}
